### ISSUE TITLE
Return value of "Phinx\Console\Command\SeedRun::execute()" must be of the type int, "null" returned

### ISSUE THREAD

**Issue by cirolaferrara** [gothinkster/slim-php-realworld-example-app#25]
Running the fresh checkout of the repository
```
git clone https://github.com/gothinkster/slim-php-realworld-example-app.git
cd slim-php-realworld-example-app
composer install
composer refresh-database
```
I have
```
PHP Fatal error:  Uncaught TypeError: Return value of "Phinx\Console\Command\SeedRun::execute()" must be of the type int, "null" returned. in /var/www/html/www.api.com/vendor/symfony/console/Command/Command.php:258
Stack trace:
#0 /var/www/html/www.api.com/vendor/symfony/console/Application.php(971): Symfony\Component\Console\Command\Command->run()
#1 /var/www/html/www.api.com/vendor/symfony/console/Application.php(290): Symfony\Component\Console\Application->doRunCommand()
#2 /var/www/html/www.api.com/vendor/robmorgan/phinx/src/Phinx/Console/PhinxApplication.php(83): Symfony\Component\Console\Application->doRun()
#3 /var/www/html/www.api.com/vendor/symfony/console/Application.php(166): Phinx\Console\PhinxApplication->doRun()
#4 /var/www/html/www.api.com/vendor/robmorgan/phinx/bin/phinx(28): Symfony\Component\Console\Application->run()
#5 {main}
  thrown in /var/www/html/www.api.com/vendor/symfony/console/Command/Command.php on line 258
Script php vendor/bin/phinx rollback -t0; php vendor/bin/phinx migrate; php vendor/bin/phinx seed:run handling the refresh-database event returned with error code 255
```
I am on Linux with PHP 7.4.3

**Comment by alexszilagyi** [comment]
@cirolaferrara : any updates for this?

**Comment by cirolaferrara** [comment]
No
